title: Trompeloeil - C++14 mocking framework
email: bjorn@fahller.se
description: >- # this means to ignore newlines until "baseurl:"
  News and noteworthy events regarding the trompeloeil C++14 mocking
  framework. Mostly release announcements.
baseurl: ""
url: ""
twitter_username: bjorn_fahller
github_username:  rollbear

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

logo: "/assets/images/trompeloeil-logo.png"


defaults:
  - values:
      show_date: true
      sidebar:
        - nav: "docs"
